
[demo]
	addr = "192.168.140.25:3306"
	dsn = "developer:111111@tcp(192.168.140.25:3306)/go_api_scaffolding_v1_0_0?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
	readDSN = ["developer:111111@tcp(192.168.140.25:3306)/go_api_scaffolding_v1_0_0?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8","developer:111111@tcp(192.168.140.25:3306)/go_api_scaffolding_v1_0_0?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="4h"
	queryTimeout = "200ms"
	execTimeout = "300ms"
	tranTimeout = "400ms"
